"""Design and verify the 26G low-pass decimating FIR coefficients."""

from pathlib import Path

import numpy as np
from scipy.signal import freqz, remez


FS_HZ = 65_000_000.0
PASSBAND_HZ = 500_000.0
STOPBAND_HZ = 1_000_000.0
DECIMATION = 38
COEFFICIENT_BITS = 18
MAX_PASSBAND_ERROR_DB = 0.01
MIN_STOPBAND_ATTENUATION_DB = 70.0
MIN_TAPS = 521
MAX_TAPS = 521
FREQ_RESPONSE_POINTS = 1 << 18
OUTPUT_PATH = Path(__file__).resolve().parents[1] / "25G_PL.srcs/sources_1/imports/coeDoc/fir_26g_decim38_q17.coe"


def quantize_q17(coefficients):
    scale = 1 << (COEFFICIENT_BITS - 1)
    quantized = np.rint(coefficients * scale).astype(np.int64)
    quantized[len(quantized) // 2] += scale - int(np.sum(quantized))

    minimum = -scale
    maximum = scale - 1
    if np.any(quantized < minimum) or np.any(quantized > maximum):
        raise ValueError("A coefficient does not fit in signed 18-bit Q1.17")
    if not np.array_equal(quantized, quantized[::-1]):
        raise ValueError("Coefficient quantization broke FIR symmetry")
    return quantized


def measure(quantized):
    scale = 1 << (COEFFICIENT_BITS - 1)
    frequency, response = freqz(
        quantized / scale,
        worN=FREQ_RESPONSE_POINTS,
        fs=FS_HZ,
    )
    magnitude_db = 20.0 * np.log10(np.maximum(np.abs(response), 1e-15))
    passband = magnitude_db[frequency <= PASSBAND_HZ]
    stopband = magnitude_db[frequency >= STOPBAND_HZ]
    at_500k_db = float(np.interp(PASSBAND_HZ, frequency, magnitude_db))
    at_1m_db = float(np.interp(STOPBAND_HZ, frequency, magnitude_db))

    return {
        "passband_min_db": float(np.min(passband)),
        "passband_max_db": float(np.max(passband)),
        "passband_error_db": float(np.max(np.abs(passband))),
        "stopband_max_db": float(np.max(stopband)),
        "at_500k_db": at_500k_db,
        "at_1m_db": at_1m_db,
    }


def design():
    passband_delta = 10.0 ** (MAX_PASSBAND_ERROR_DB / 20.0) - 1.0
    stopband_delta = 10.0 ** (-MIN_STOPBAND_ATTENUATION_DB / 20.0)
    weights = [1.0 / passband_delta, 1.0 / stopband_delta]
    bands = [0.0, PASSBAND_HZ, STOPBAND_HZ, FS_HZ / 2.0]

    for taps in range(MIN_TAPS | 1, MAX_TAPS + 1, 2):
        try:
            coefficients = remez(
                taps,
                bands,
                [1.0, 0.0],
                weight=weights,
                fs=FS_HZ,
                maxiter=200,
                grid_density=32,
            )
        except ValueError:
            continue

        coefficients /= np.sum(coefficients)
        quantized = quantize_q17(coefficients)
        metrics = measure(quantized)
        if (
            metrics["passband_error_db"] <= MAX_PASSBAND_ERROR_DB
            and metrics["stopband_max_db"]
            <= -MIN_STOPBAND_ATTENUATION_DB
        ):
            return quantized, metrics

    raise RuntimeError(f"No valid design found through {MAX_TAPS} taps")


def write_coe(path, quantized, metrics):
    lines = [
        "; 26G real low-pass FIR, generated by design_26g_fir.py",
        (
            f"; Fs={FS_HZ:.1f} Hz, decimation={DECIMATION}, "
            f"passband=0..{PASSBAND_HZ:.1f} Hz, "
            f"stopband={STOPBAND_HZ:.1f} Hz..Nyquist"
        ),
        (
            f"; taps={len(quantized)}, order={len(quantized) - 1}, "
            f"signed_bits={COEFFICIENT_BITS}, sum={int(np.sum(quantized))}"
        ),
        (
            f"; passband=[{metrics['passband_min_db']:.6f}, "
            f"{metrics['passband_max_db']:.6f}] dB, "
            f"500kHz={metrics['at_500k_db']:.6f} dB"
        ),
        (
            f"; stopband_max={metrics['stopband_max_db']:.6f} dB, "
            f"1MHz={metrics['at_1m_db']:.6f} dB"
        ),
        "radix=10;",
        "coefdata=",
    ]
    lines.extend(
        f"{value}{';' if index == len(quantized) - 1 else ','}"
        for index, value in enumerate(quantized)
    )
    path.write_text("\n".join(lines) + "\n", encoding="ascii")


def main():
    quantized, metrics = design()
    write_coe(OUTPUT_PATH, quantized, metrics)

    print(f"taps={len(quantized)}, order={len(quantized) - 1}")
    print(f"output_sample_rate={FS_HZ / DECIMATION:.6f} Hz")
    print(f"500_kHz={metrics['at_500k_db']:.6f} dB")
    print(f"passband_error={metrics['passband_error_db']:.6f} dB")
    print(f"1_MHz={metrics['at_1m_db']:.6f} dB")
    print(f"stopband_max={metrics['stopband_max_db']:.6f} dB")
    print(f"coefficient_sum={int(np.sum(quantized))}")
    print(f"wrote={OUTPUT_PATH}")


if __name__ == "__main__":
    main()
