################################################################################
# AD9226 interface, board clock, and reset
################################################################################

set_property IOSTANDARD LVCMOS33 [get_ports {i_ad_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_ad_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_ad_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_ad_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_ad_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_ad_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_ad_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_ad_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_ad_data[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_ad_data[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_ad_data[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_ad_data[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports i_clk_50m]
set_property IOSTANDARD LVCMOS33 [get_ports i_rst]
set_property IOSTANDARD LVCMOS33 [get_ports o_ad_clk]

set_property PACKAGE_PIN T15 [get_ports {i_ad_data[0]}]
set_property PACKAGE_PIN U13 [get_ports {i_ad_data[1]}]
set_property PACKAGE_PIN V13 [get_ports {i_ad_data[2]}]
set_property PACKAGE_PIN V12 [get_ports {i_ad_data[3]}]
set_property PACKAGE_PIN W13 [get_ports {i_ad_data[4]}]
set_property PACKAGE_PIN T12 [get_ports {i_ad_data[5]}]
set_property PACKAGE_PIN U12 [get_ports {i_ad_data[6]}]
set_property PACKAGE_PIN T11 [get_ports {i_ad_data[7]}]
set_property PACKAGE_PIN T10 [get_ports {i_ad_data[8]}]
set_property PACKAGE_PIN B19 [get_ports {i_ad_data[9]}]
set_property PACKAGE_PIN A20 [get_ports {i_ad_data[10]}]
set_property PACKAGE_PIN C20 [get_ports {i_ad_data[11]}]
set_property PACKAGE_PIN T14 [get_ports o_ad_clk]
set_property PACKAGE_PIN U18 [get_ports i_clk_50m]
set_property PACKAGE_PIN N15 [get_ports i_rst]
