#ifndef AD_FIFO_MONITOR_AXI_H
#define AD_FIFO_MONITOR_AXI_H

#include "xil_io.h"
#include "xil_types.h"
#include "xstatus.h"

#define AD_FIFO_MONITOR_AXI_CONTROL_OFFSET             0x00U
#define AD_FIFO_MONITOR_AXI_STATUS_OFFSET              0x04U
#define AD_FIFO_MONITOR_AXI_VERSION_OFFSET             0x08U
#define AD_FIFO_MONITOR_AXI_ADC_SAMPLE_LO_OFFSET       0x10U
#define AD_FIFO_MONITOR_AXI_ADC_SAMPLE_HI_OFFSET       0x14U
#define AD_FIFO_MONITOR_AXI_FIFO_WRITE_LO_OFFSET       0x18U
#define AD_FIFO_MONITOR_AXI_FIFO_WRITE_HI_OFFSET       0x1CU
#define AD_FIFO_MONITOR_AXI_BLOCKED_HIGH_LO_OFFSET     0x20U
#define AD_FIFO_MONITOR_AXI_BLOCKED_HIGH_HI_OFFSET     0x24U
#define AD_FIFO_MONITOR_AXI_BLOCKED_RESET_LO_OFFSET    0x28U
#define AD_FIFO_MONITOR_AXI_BLOCKED_RESET_HI_OFFSET    0x2CU
#define AD_FIFO_MONITOR_AXI_AXIS_BEAT_LO_OFFSET        0x30U
#define AD_FIFO_MONITOR_AXI_AXIS_BEAT_HI_OFFSET        0x34U
#define AD_FIFO_MONITOR_AXI_FRAME_LO_OFFSET            0x38U
#define AD_FIFO_MONITOR_AXI_FRAME_HI_OFFSET            0x3CU
#define AD_FIFO_MONITOR_AXI_AXIS_STALL_LO_OFFSET       0x40U
#define AD_FIFO_MONITOR_AXI_AXIS_STALL_HI_OFFSET       0x44U
#define AD_FIFO_MONITOR_AXI_LAST_FRAME_TIME_LO_OFFSET  0x48U
#define AD_FIFO_MONITOR_AXI_LAST_FRAME_TIME_HI_OFFSET  0x4CU

#define AD_FIFO_MONITOR_AXI_CONTROL_SNAPSHOT_MASK      0x00000001U
#define AD_FIFO_MONITOR_AXI_CONTROL_CLEAR_STICKY_MASK  0x00000002U

#define AD_FIFO_MONITOR_AXI_STATUS_SNAPSHOT_BUSY_MASK  0x00000001U
#define AD_FIFO_MONITOR_AXI_STATUS_SNAPSHOT_VALID_MASK 0x00000002U
#define AD_FIFO_MONITOR_AXI_STATUS_CLEAR_BUSY_MASK     0x00000004U
#define AD_FIFO_MONITOR_AXI_STATUS_WRITE_BLOCKED_MASK  0x00000008U
#define AD_FIFO_MONITOR_AXI_STATUS_FIFO_FULL_MASK      0x00000010U
#define AD_FIFO_MONITOR_AXI_STATUS_PROG_FULL_MASK      0x00000020U
#define AD_FIFO_MONITOR_AXI_STATUS_FULL_LIVE_MASK      0x00000040U
#define AD_FIFO_MONITOR_AXI_STATUS_WR_RESET_BUSY_MASK  0x00000080U
#define AD_FIFO_MONITOR_AXI_STATUS_RD_RESET_BUSY_MASK  0x00000100U

#define AD_FIFO_MONITOR_AXI_VERSION                    0x00010000U

#define AD_FIFO_MONITOR_AXI_mWriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))

#define AD_FIFO_MONITOR_AXI_mReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))

XStatus AD_FIFO_MONITOR_AXI_Reg_SelfTest(void *baseaddr_p);

#endif
